# Generated by Django 4.2.1 on 2023-06-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_rename_searches_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='text',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
