# Generated by Django 4.2.1 on 2023-06-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_alter_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
