# Generated by Django 4.2.1 on 2023-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
