# Generated by Django 4.2.1 on 2023-07-19 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_link_href_alter_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
